/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_01_lemonfruitshop;

import kelompok_01_lemonfruitshop.Buah;
import kelompok_01_lemonfruitshop.DbHandler;

/**
 *
 *
 */
public class Buahupdatestok extends javax.swing.JFrame {
    DbHandler a = new DbHandler();
    
    
    
    
    public Buahupdatestok() {
        initComponents();
      
        this.success1.setText("");
        this.invalid.setText("");
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        angkatan_search = new javax.swing.JTextField();
        FID = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        ID_Buah = new javax.swing.JLabel();
        Stok = new javax.swing.JLabel();
        success1 = new javax.swing.JLabel();
        FStok = new javax.swing.JTextField();
        Text = new javax.swing.JLabel();
        invalid = new javax.swing.JLabel();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDActionPerformed(evt);
            }
        });

        Add.setText("add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        ID_Buah.setText("Masukan ID_Buah");

        Stok.setText("Input Stok Buah");

        success1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        success1.setForeground(new java.awt.Color(0, 153, 0));
        success1.setText("Success !");

        Text.setText("Update Stok Buah");

        invalid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalid.setForeground(new java.awt.Color(0, 153, 0));
        invalid.setText("invalid id!");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invalid)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Stok)
                            .addComponent(ID_Buah)
                            .addComponent(success1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FStok, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update)
                                .addGap(9, 9, 9)
                                .addComponent(Add)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_Buah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stok))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(success1)
                    .addComponent(Add)
                    .addComponent(update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
 if(this.FID.getText().isEmpty() ){
 this.invalid.setText("Required !");
         }
  
        else{
            
        a.connect("localhost", "db_lemonshop", "root", "yohana2809");
         Buah p =  a.addStok(this.FID.getText(), this.FStok.getText());
        
            this.invalid.setText("Stok Berhasil ditambahkan");
           
           
            this.success1.setText(" ");
            this.FStok.setText("");
            this.FID.setText("");
            }
            
            
        
        a.disconnect();    
     
    }//GEN-LAST:event_AddActionPerformed

    private void FIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
   
        if(this.FID.getText().isEmpty() ){
            this.invalid.setText("Required !");
        }
        
        
        
        
        else{
            
        a.connect("localhost", "db_lemonshop", "root", "yohana2809");
         Buah p =  a.updateStok(this.FID.getText(), this.FStok.getText());
        
            this.invalid.setText("Stok berhasil diubah ");
           
           
            this.success1.setText(" ");
            this.FStok.setText("");
            this.FID.setText("");
            }
            
            
        
        a.disconnect();
                // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buahupdatestok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buahupdatestok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buahupdatestok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buahupdatestok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buahupdatestok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField FID;
    private javax.swing.JTextField FStok;
    private javax.swing.JLabel ID_Buah;
    private javax.swing.JLabel Stok;
    private javax.swing.JLabel Text;
    private javax.swing.JTextField angkatan_search;
    private javax.swing.JLabel invalid;
    private javax.swing.JLabel success1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
