package kelompok_01_lemonfruitshop;

import java.util.List;
import java.util.ArrayList;


public class LaporanLihat extends javax.swing.JFrame {
    LaporanTulis add = new LaporanTulis();
    List<Laporan> lapo = new ArrayList<Laporan>();
    DbHandler b = new DbHandler();
    int lps = 0;
    int maxi = 0;

    /**
     * Creates new form LaporanLihat
     */
    public LaporanLihat() {
        initComponents();
        add.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        refresh();
        reset();
    }
    
    public void refresh(){
        b.connect("localhost","db_lemonshop","root","Sidabutar");
        this.lapo = b.getalllaporan();
        this.maxi = b.counter;
        b.disconnect();
    }
    
    public void reset(){
        if(this.maxi > 0) {
            this.lps = 0;
            this.nolap.setText ("No.Laporan : " + lapo.get(0).getNomor());
            this.jenislap.setText ("Jenis Laporan : " + lapo.get(0).getJenis());
            this.tanggallap.setText ("Tanggal Laporan : " + lapo.get(0).getTanggal());
        } else {
            this.nolap.setText ("No.Laporan : " );
            this.jenislap.setText ("Jenis Laporan : ");
            this.tanggallap.setText ("Tanggal Laporan : ");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nolap = new javax.swing.JLabel();
        jenislap = new javax.swing.JLabel();
        tanggallap = new javax.swing.JLabel();
        nextbb = new javax.swing.JButton();
        prevbb = new javax.swing.JButton();
        addbb = new javax.swing.JButton();
        refbb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lihat Laporan");

        nolap.setText("No.Laporan");

        jenislap.setText("Jenis Laporan");

        tanggallap.setText("Tanggal Laporan");

        nextbb.setText("Next");
        nextbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbbActionPerformed(evt);
            }
        });

        prevbb.setText("Prev");
        prevbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevbbActionPerformed(evt);
            }
        });

        addbb.setText("Add");
        addbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbbActionPerformed(evt);
            }
        });

        refbb.setText("Refresh");
        refbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(prevbb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextbb))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nolap)
                    .addComponent(jenislap)
                    .addComponent(tanggallap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(refbb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addbb))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addbb)
                    .addComponent(refbb))
                .addGap(30, 30, 30)
                .addComponent(nolap)
                .addGap(18, 18, 18)
                .addComponent(jenislap)
                .addGap(18, 18, 18)
                .addComponent(tanggallap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextbb)
                    .addComponent(prevbb)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevbbActionPerformed
        refresh();
        if(this.maxi > 0) {
            lps = (lps + 1) % maxi;
            this.nolap.setText ("No.Laporan : " + lapo.get(lps).getNomor());
            this.jenislap.setText ("Jenis Laporan : " + lapo.get(lps).getJenis());
            this.tanggallap.setText ("Tanggal Laporan : " + lapo.get(lps).getTanggal());
        }
    }//GEN-LAST:event_prevbbActionPerformed

    private void addbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbbActionPerformed
        add.setVisible(true);
    }//GEN-LAST:event_addbbActionPerformed

    private void nextbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbbActionPerformed
       refresh();
        if(this.maxi > 0) {
            lps = (lps + 1) % maxi;
            this.nolap.setText ("No.Laporan : " + lapo.get(lps).getNomor());
            this.jenislap.setText ("Jenis Laporan : " + lapo.get(lps).getJenis());
            this.tanggallap.setText ("Tanggal Laporan : " + lapo.get(lps).getTanggal());
        }
    }//GEN-LAST:event_nextbbActionPerformed

    private void refbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refbbActionPerformed
       refresh();
       reset();
    }//GEN-LAST:event_refbbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanLihat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanLihat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanLihat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanLihat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanLihat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jenislap;
    private javax.swing.JButton nextbb;
    private javax.swing.JLabel nolap;
    private javax.swing.JButton prevbb;
    private javax.swing.JButton refbb;
    private javax.swing.JLabel tanggallap;
    // End of variables declaration//GEN-END:variables
}
