
package lemonshop;

import java.util.List;
import java.util.ArrayList;

public class DataBuah extends javax.swing.JFrame {
    DbHandler a = new DbHandler();
  
    List<Buah>  buah = new ArrayList<Buah>();
    int max = 0 ;
    int idx = 0 ;

   
    public DataBuah() {
        initComponents();
        refresh();
        reset();
        
      
    }

    
    public void refresh(){
        a.connect("localhost", "db_lemonshop", "root", "yohana2809");
        this.buah = a.getallbuah();
        this.max = a.counter;
        a.disconnect();
        
        
        
    }
    
    public void reset(){
        if(this.max > 0){
            this.idx = 0;
            this.label_idbuah.setText("ID Buah : " + buah.get(0).getID_buah());
            this.label_nama.setText("Nama Buah : " + buah.get(0).getName());
            this.label_Harga.setText("Harga : " + buah.get(0).getHarga());
            this.label_stok.setText("Stok : " +buah.get(0).getStok());
            this.label_kadaluarsa.setText("Tanggal Kadaluarsa : " + buah.get(0).getkadaluarsa());
           
        }else{
            this.label_idbuah.setText("ID Buah : " );
            this.label_nama.setText("Nama Buah : " );
           this.label_Harga.setText("Harga : " );
            this.label_stok.setText("Stok : " );
            this.label_kadaluarsa.setText("Tanggal Kadaluarsa : " );
           
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_idbuah = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_Harga = new javax.swing.JLabel();
        label_stok = new javax.swing.JLabel();
        buttonnext = new javax.swing.JButton();
        buttonprev = new javax.swing.JButton();
        buttonreftresh = new javax.swing.JButton();
        label_kadaluarsa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Data Buah Lemon Shop");

        label_idbuah.setText("ID Buah : ");

        label_nama.setText("Nama : ");

        label_Harga.setText("Harga :");

        label_stok.setText("Stok :");

        buttonnext.setText("Next");
        buttonnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnextActionPerformed(evt);
            }
        });

        buttonprev.setText("Prev");
        buttonprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonprevActionPerformed(evt);
            }
        });

        buttonreftresh.setText("Refresh");
        buttonreftresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonreftreshActionPerformed(evt);
            }
        });

        label_kadaluarsa.setText("Tanggal Kadaluarsa :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(0, 133, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_idbuah)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_kadaluarsa)
                            .addComponent(label_stok)
                            .addComponent(label_Harga)
                            .addComponent(label_nama))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonreftresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonprev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonnext)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(label_idbuah)
                .addGap(18, 18, 18)
                .addComponent(label_nama)
                .addGap(18, 18, 18)
                .addComponent(label_Harga)
                .addGap(18, 18, 18)
                .addComponent(label_stok)
                .addGap(17, 17, 17)
                .addComponent(label_kadaluarsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonnext)
                    .addComponent(buttonprev)
                    .addComponent(buttonreftresh))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonprevActionPerformed
        // TODO add your handling code here:
        refresh();
        if(this.max > 0){
        this.idx = (idx + (max-1)) % max;
            this.label_idbuah.setText("ID Buah : " + buah.get(idx).getID_buah());
            this.label_nama.setText("Nama Buah : " + buah.get(idx).getName());
           this.label_Harga.setText("Harga : " + buah.get(idx).getHarga());
            this.label_stok.setText("Stok : " +buah.get(idx).getStok());
            this.label_kadaluarsa.setText("Tanggal Kadaluarsa : " + buah.get(idx).getkadaluarsa());
           
        
        }
        
        
    }//GEN-LAST:event_buttonprevActionPerformed

    private void buttonnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnextActionPerformed
        // TODO add your handling code here:
        refresh();
        if(this.max > 0){
        idx = (idx + 1) % max;
        this.label_idbuah.setText("ID Buah : " + buah.get(idx).getID_buah());
            this.label_nama.setText("Nama Buah : " + buah.get(idx).getName());
               this.label_Harga.setText("Harga : " + buah.get(idx).getHarga());
            this.label_stok.setText("Stok : " +buah.get(idx).getStok());
            this.label_kadaluarsa.setText("Tanggal Kadaluarsa : " + buah.get(idx).getkadaluarsa());
        }
    }//GEN-LAST:event_buttonnextActionPerformed

    private void buttonreftreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonreftreshActionPerformed
        // TODO add your handling code here:
        refresh();
        reset();
    }//GEN-LAST:event_buttonreftreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBuah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBuah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBuah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBuah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBuah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonnext;
    private javax.swing.JButton buttonprev;
    private javax.swing.JButton buttonreftresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_Harga;
    private javax.swing.JLabel label_idbuah;
    private javax.swing.JLabel label_kadaluarsa;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_stok;
    // End of variables declaration//GEN-END:variables
}
